language: node_js
node_js:
  - "10"
services:
  - docker
branches:
  only:
    - master

before_install:
  - npm install

script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t pea3nut/pxer-homepage:latest .
  - docker push qiyang14/god_of_stock:latest

